	.INSERT "ZORK3FREQ"
	.INSERT "ZORK3DAT"			; DATA IS IN THIS FILE
	.INSERT "GSYNTAX"
	.INSERT "GMACROS"
	.INSERT "GCLOCK"
	.INSERT "GMAIN"
	.INSERT "GPARSER"
	.INSERT "3DUNGEON"
	.INSERT "GGLOBALS"
	.INSERT "GVERBS"
	.INSERT "3ACTIONS"
	.INSERT "ZORK3STR"
	.END
